# Generated by Django 5.0 on 2024-12-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_bagianareakerjanakes_tingkatpendidikan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tingkatpendidikan',
            old_name='nama',
            new_name='name',
        ),
    ]
