# Generated by Django 5.0 on 2024-12-07 09:06

import apps.webapp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_nama_tingkatpendidikan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssesmensScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pendidikanpelatihannakes',
            name='graduation_year',
            field=models.IntegerField(default=apps.webapp.models.current_year, validators=[django.core.validators.MinValueValidator(1984), apps.webapp.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='pendidikanpelatihannakes',
            name='institusi',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pendidikanpelatihannakes',
            name='jurusan',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='pendidikanpelatihannakes',
            name='profesi',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='starting_work',
            field=models.DateField(default=apps.webapp.models.current_year, validators=[django.core.validators.MinValueValidator(1984), apps.webapp.models.max_value_current_year]),
        ),
        migrations.CreateModel(
            name='SelfAssesmentNakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian_kewenangan', models.TextField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.selfassesmensscore')),
            ],
        ),
    ]
