# Generated by Django 5.0 on 2024-12-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_selfassesmensscore_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfAssesmensScore',
            new_name='SelfAssesmentScore',
        ),
    ]
