# Generated by Django 5.0 on 2024-12-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_kondisikesehatan_pelatihannakes_pengalamankerja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitasnakes',
            name='full_name',
        ),
        migrations.AddField(
            model_name='identitasnakes',
            name='profesi_nakes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapp.profesinakes'),
            preserve_default=False,
        ),
    ]
