# Generated by Django 5.0 on 2024-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_identitasnakes_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitasnakes',
            name='starting_work',
            field=models.DateField(null=True),
        ),
    ]
