# Generated by Django 5.0 on 2024-12-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_identitasnakes_starting_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitasnakes',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='mobile_phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='nip_nps',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='no_ijazah',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='no_sip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='no_str',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='place_of_birth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identitasnakes',
            name='profesi_nakes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.profesinakes'),
        ),
    ]
